#!/usr/bin/env python3
"""
SEN2NEON Reflectance Normalization
==================================

Converts SEN2NEON uint16 reflectance to float32.

SEN2NEON storage:
    reflectance_uint16 = reflectance * 10000

Therefore:
    reflectance = reflectance_uint16 / 10000.0

This script operates on the patch index generated by
create_patches.py.

IMPORTANT:
    It does not create another copy of all image patches.

Instead, it provides:
    1. A normalization utility.
    2. Dataset-level statistics computed ONLY from TRAIN.
    3. Validation of reflectance ranges.
    4. A normalization configuration for the training pipeline.

The actual PyTorch Dataset will later apply:
    uint16 -> float32 -> /10000

when reading each patch.

This avoids unnecessary disk usage.
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path
from typing import Dict, Optional, Tuple

import numpy as np
import pandas as pd
import rasterio
from rasterio.windows import Window


# ============================================================
# CONSTANTS
# ============================================================

NUM_BANDS = 12

REFLECTANCE_SCALE = 10000.0

LR_NODATA = 65535
HR_NODATA = 0

EXPECTED_LR_PATCH = 64
EXPECTED_HR_PATCH = 256

DEFAULT_SAMPLE_PATCHES = 1000


# ============================================================
# BAND INFORMATION
# ============================================================

BAND_NAMES = [
    "B1",
    "B2",
    "B3",
    "B4",
    "B5",
    "B6",
    "B7",
    "B8",
    "B8A",
    "B9",
    "B11",
    "B12",
]


# ============================================================
# LOGGING
# ============================================================

def log(message: str = "") -> None:
    print(message, flush=True)


def fail(message: str) -> None:
    print(
        f"\nERROR: {message}",
        file=sys.stderr,
    )
    raise SystemExit(1)


# ============================================================
# ARGUMENTS
# ============================================================

def parse_args() -> argparse.Namespace:

    parser = argparse.ArgumentParser(
        description=(
            "Validate and configure SEN2NEON "
            "reflectance normalization."
        )
    )

    parser.add_argument(
        "--data-root",
        type=Path,
        default=Path("SEN2NEON_5GB"),
        help="SEN2NEON dataset root.",
    )

    parser.add_argument(
        "--patch-index",
        type=Path,
        default=None,
        help=(
            "Patch index CSV. "
            "Default: <data-root>/patches/all_patches.csv"
        ),
    )

    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help=(
            "Output directory. "
            "Default: <data-root>/normalization"
        ),
    )

    parser.add_argument(
        "--sample-patches",
        type=int,
        default=DEFAULT_SAMPLE_PATCHES,
        help=(
            "Number of training patches to inspect. "
            "Default: 1000."
        ),
    )

    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random sampling seed.",
    )

    parser.add_argument(
        "--verify-only",
        action="store_true",
        help=(
            "Only verify normalization assumptions; "
            "do not calculate statistics."
        ),
    )

    return parser.parse_args()


# ============================================================
# NORMALIZATION
# ============================================================

def normalize_reflectance(
    array: np.ndarray,
    nodata: int,
) -> Tuple[np.ndarray, np.ndarray]:
    """
    Convert uint16 reflectance to float32.

    Returns:
        normalized:
            float32 reflectance

        valid_mask:
            bool array where True means valid
    """

    if array.dtype != np.uint16:
        raise ValueError(
            f"Expected uint16 input, got {array.dtype}"
        )

    valid_mask = array != nodata

    normalized = (
        array.astype(np.float32)
        / REFLECTANCE_SCALE
    )

    # --------------------------------------------------------
    # Nodata is not physical reflectance.
    #
    # Keep it as 0 numerically, but always use the mask to
    # distinguish it from actual valid pixels.
    # --------------------------------------------------------

    normalized[~valid_mask] = 0.0

    # --------------------------------------------------------
    # Physical reflectance should not be negative.
    # --------------------------------------------------------

    normalized = np.maximum(
        normalized,
        0.0,
    )

    return normalized, valid_mask


# ============================================================
# VALIDATE NORMALIZATION
# ============================================================

def validate_normalization() -> None:

    log()
    log("=" * 72)
    log("NORMALIZATION SELF-TEST")
    log("=" * 72)

    test_values = np.array(
        [
            0,
            1,
            100,
            1000,
            5000,
            10000,
        ],
        dtype=np.uint16,
    )

    normalized, mask = normalize_reflectance(
        test_values,
        nodata=65535,
    )

    expected = np.array(
        [
            0.0,
            0.0001,
            0.01,
            0.1,
            0.5,
            1.0,
        ],
        dtype=np.float32,
    )

    if not np.allclose(
        normalized,
        expected,
        atol=1e-7,
    ):
        raise RuntimeError(
            "Normalization self-test failed."
        )

    if not np.all(mask):
        raise RuntimeError(
            "Unexpected invalid pixels in self-test."
        )

    # Test nodata.
    nodata_test = np.array(
        [
            0,
            10000,
            65535,
        ],
        dtype=np.uint16,
    )

    normalized, mask = normalize_reflectance(
        nodata_test,
        nodata=65535,
    )

    if mask.tolist() != [
        True,
        True,
        False,
    ]:
        raise RuntimeError(
            "Nodata mask self-test failed."
        )

    if not math.isclose(
        float(normalized[1]),
        1.0,
        abs_tol=1e-7,
    ):
        raise RuntimeError(
            "Reflectance scaling self-test failed."
        )

    log("PASS: uint16 -> float32 scaling")
    log("PASS: nodata masking")
    log("PASS: non-negative clipping")
    log()
    log("Normalization self-test PASSED.")


# ============================================================
# READ PATCH
# ============================================================

def read_patch_from_index(
    row: pd.Series,
    data_root: Path,
    use_hr: bool,
) -> Tuple[np.ndarray, np.ndarray]:

    path_column = (
        "hr_path"
        if use_hr
        else "lr_path"
    )

    x_column = (
        "hr_x"
        if use_hr
        else "lr_x"
    )

    y_column = (
        "hr_y"
        if use_hr
        else "lr_y"
    )

    size_column = (
        "hr_size"
        if use_hr
        else "lr_size"
    )

    nodata = (
        HR_NODATA
        if use_hr
        else LR_NODATA
    )

    path = Path(
        str(row[path_column])
    )

    if not path.is_absolute():
        path = data_root / path

    x = int(row[x_column])
    y = int(row[y_column])
    size = int(row[size_column])

    window = Window(
        col_off=x,
        row_off=y,
        width=size,
        height=size,
    )

    with rasterio.open(path) as src:

        array = src.read(
            window=window,
        )

    normalized, valid_mask = (
        normalize_reflectance(
            array,
            nodata,
        )
    )

    return normalized, valid_mask


# ============================================================
# ONLINE STATISTICS
# ============================================================

class RunningStatistics:
    """
    Numerically stable per-band statistics.

    Computes:
        count
        mean
        variance
        min
        max

    Only valid pixels are included.
    """

    def __init__(
        self,
        num_bands: int,
    ) -> None:

        self.num_bands = num_bands

        self.count = np.zeros(
            num_bands,
            dtype=np.int64,
        )

        self.mean = np.zeros(
            num_bands,
            dtype=np.float64,
        )

        self.M2 = np.zeros(
            num_bands,
            dtype=np.float64,
        )

        self.minimum = np.full(
            num_bands,
            np.inf,
            dtype=np.float64,
        )

        self.maximum = np.full(
            num_bands,
            -np.inf,
            dtype=np.float64,
        )

    def update(
        self,
        values: np.ndarray,
        valid_mask: np.ndarray,
    ) -> None:

        if values.ndim != 3:
            raise ValueError(
                f"Expected [bands,H,W], got {values.shape}"
            )

        for band in range(
            self.num_bands
        ):

            band_values = values[
                band
            ][
                valid_mask[band]
            ].astype(
                np.float64,
                copy=False,
            )

            if band_values.size == 0:
                continue

            batch_count = band_values.size

            batch_mean = float(
                band_values.mean()
            )

            batch_min = float(
                band_values.min()
            )

            batch_max = float(
                band_values.max()
            )

            if self.count[band] == 0:

                self.count[band] = (
                    batch_count
                )

                self.mean[band] = (
                    batch_mean
                )

                self.M2[band] = float(
                    np.sum(
                        (
                            band_values
                            - batch_mean
                        ) ** 2
                    )
                )

            else:

                old_count = int(
                    self.count[band]
                )

                old_mean = (
                    self.mean[band]
                )

                old_M2 = (
                    self.M2[band]
                )

                new_count = (
                    old_count
                    + batch_count
                )

                delta = (
                    batch_mean
                    - old_mean
                )

                new_mean = (
                    old_mean
                    + delta
                    * batch_count
                    / new_count
                )

                batch_M2 = float(
                    np.sum(
                        (
                            band_values
                            - batch_mean
                        ) ** 2
                    )
                )

                new_M2 = (
                    old_M2
                    + batch_M2
                    + (
                        delta ** 2
                        * old_count
                        * batch_count
                        / new_count
                    )
                )

                self.count[band] = (
                    new_count
                )

                self.mean[band] = (
                    new_mean
                )

                self.M2[band] = (
                    new_M2
                )

            self.minimum[band] = min(
                self.minimum[band],
                batch_min,
            )

            self.maximum[band] = max(
                self.maximum[band],
                batch_max,
            )

    def finalize(self) -> Dict:

        variance = np.zeros(
            self.num_bands,
            dtype=np.float64,
        )

        for band in range(
            self.num_bands
        ):

            if self.count[band] > 1:
                variance[band] = (
                    self.M2[band]
                    / (
                        self.count[band]
                        - 1
                    )
                )

        std = np.sqrt(
            np.maximum(
                variance,
                0.0,
            )
        )

        result = {
            "count": self.count.tolist(),
            "mean": self.mean.tolist(),
            "std": std.tolist(),
            "min": self.minimum.tolist(),
            "max": self.maximum.tolist(),
        }

        return result


# ============================================================
# COMPUTE TRAIN STATISTICS
# ============================================================

def compute_training_statistics(
    patch_index: pd.DataFrame,
    data_root: Path,
    sample_patches: int,
    seed: int,
) -> Dict:

    train_df = patch_index[
        patch_index["split"] == "train"
    ].copy()

    if train_df.empty:
        raise RuntimeError(
            "No training patches found."
        )

    if sample_patches > 0:
        sample_count = min(
            sample_patches,
            len(train_df),
        )

        train_df = train_df.sample(
            n=sample_count,
            random_state=seed,
        )

    log()
    log("=" * 72)
    log("TRAINING REFLECTANCE STATISTICS")
    log("=" * 72)

    log(
        f"Training patches available: "
        f"{len(patch_index[patch_index['split'] == 'train'])}"
    )

    log(
        f"Patches sampled: "
        f"{len(train_df)}"
    )

    log()
    log(
        "Calculating statistics from "
        "valid LR reflectance pixels..."
    )

    stats = RunningStatistics(
        NUM_BANDS
    )

    processed = 0
    failures = 0

    for index, (_, row) in enumerate(
        train_df.iterrows(),
        start=1,
    ):

        try:

            values, valid_mask = (
                read_patch_from_index(
                    row=row,
                    data_root=data_root,
                    use_hr=False,
                )
            )

            stats.update(
                values,
                valid_mask,
            )

            processed += 1

        except Exception as exc:

            failures += 1

            log(
                f"WARNING: failed patch "
                f"{index}: {exc}"
            )

        if (
            index == 1
            or index % 100 == 0
            or index == len(train_df)
        ):

            log(
                f"Processed "
                f"{index}/{len(train_df)}"
            )

    result = stats.finalize()

    result["bands"] = BAND_NAMES

    result["sampled_patches"] = (
        int(len(train_df))
    )

    result["processed_patches"] = (
        int(processed)
    )

    result["failed_patches"] = (
        int(failures)
    )

    result["normalization"] = {
        "method": "reflectance_scale",
        "formula": "uint16 / 10000.0",
        "scale": REFLECTANCE_SCALE,
        "nodata": LR_NODATA,
    }

    return result


# ============================================================
# RANGE VALIDATION
# ============================================================

def validate_dataset_ranges(
    patch_index: pd.DataFrame,
    data_root: Path,
    sample_patches: int,
    seed: int,
) -> Dict:

    log()
    log("=" * 72)
    log("REFLECTANCE RANGE VALIDATION")
    log("=" * 72)

    rng = np.random.default_rng(
        seed
    )

    sample_count = min(
        sample_patches,
        len(patch_index),
    )

    if sample_count == 0:
        raise RuntimeError(
            "Patch index is empty."
        )

    indices = rng.choice(
        len(patch_index),
        size=sample_count,
        replace=False,
    )

    sampled = patch_index.iloc[
        indices
    ]

    global_min = np.inf
    global_max = -np.inf

    values_over_one = 0
    negative_values = 0

    for _, row in sampled.iterrows():

        try:

            values, valid = (
                read_patch_from_index(
                    row=row,
                    data_root=data_root,
                    use_hr=False,
                )
            )

            valid_values = values[
                valid
            ]

            if valid_values.size == 0:
                continue

            global_min = min(
                global_min,
                float(
                    valid_values.min()
                ),
            )

            global_max = max(
                global_max,
                float(
                    valid_values.max()
                ),
            )

            values_over_one += int(
                np.count_nonzero(
                    valid_values > 1.0
                )
            )

            negative_values += int(
                np.count_nonzero(
                    valid_values < 0.0
                )
            )

        except Exception as exc:

            log(
                f"WARNING: validation failed: "
                f"{exc}"
            )

    result = {
        "sampled_patches": int(
            sample_count
        ),
        "minimum_valid_reflectance": (
            None
            if not np.isfinite(global_min)
            else global_min
        ),
        "maximum_valid_reflectance": (
            None
            if not np.isfinite(global_max)
            else global_max
        ),
        "values_above_one": int(
            values_over_one
        ),
        "negative_values": int(
            negative_values
        ),
    }

    log(
        f"Minimum: {global_min:.8f}"
    )

    log(
        f"Maximum: {global_max:.8f}"
    )

    log(
        f"Values > 1.0: "
        f"{values_over_one}"
    )

    log(
        f"Negative values: "
        f"{negative_values}"
    )

    return result


# ============================================================
# CONFIGURATION
# ============================================================

def create_normalization_config(
    statistics: Optional[Dict],
    range_validation: Optional[Dict],
) -> Dict:

    config = {
        "dataset": "SEN2NEON",

        "bands": BAND_NAMES,

        "num_bands": NUM_BANDS,

        "storage": {
            "dtype": "uint16",
            "scale_factor": 10000.0,
        },

        "model_input": {
            "dtype": "float32",
            "range": [0.0, 1.0],
            "formula": "uint16 / 10000.0",
        },

        "nodata": {
            "lr": LR_NODATA,
            "hr": HR_NODATA,
            "handling": (
                "replace_with_zero_and_use_valid_mask"
            ),
        },

        "important": [
            "Do not perform per-image min-max normalization.",
            "Do not independently normalize each spectral band.",
            "Keep the physical reflectance scaling consistent.",
            "Always keep a validity mask for nodata pixels.",
        ],
    }

    if statistics is not None:
        config["training_statistics"] = statistics

    if range_validation is not None:
        config["range_validation"] = (
            range_validation
        )

    return config


# ============================================================
# MAIN
# ============================================================

def main() -> None:

    args = parse_args()

    validate_normalization()

    data_root = args.data_root

    if not data_root.exists():
        fail(
            f"Dataset root does not exist: "
            f"{data_root}"
        )

    patch_index = (
        args.patch_index
        if args.patch_index is not None
        else (
            data_root
            / "patches"
            / "all_patches.csv"
        )
    )

    output_dir = (
        args.output_dir
        if args.output_dir is not None
        else (
            data_root
            / "normalization"
        )
    )

    output_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    log()
    log("=" * 72)
    log("SEN2NEON NORMALIZATION")
    log("=" * 72)

    log(
        f"Data root: {data_root}"
    )

    log(
        f"Patch index: {patch_index}"
    )

    if not patch_index.exists():
        fail(
            f"Patch index not found: "
            f"{patch_index}\n"
            "Run create_patches.py first."
        )

    patch_df = pd.read_csv(
        patch_index
    )

    if patch_df.empty:
        fail(
            "Patch index is empty."
        )

    if "split" not in patch_df.columns:
        fail(
            "Patch index does not contain "
            "the 'split' column."
        )

    log(
        f"Total patches: "
        f"{len(patch_df)}"
    )

    for split in [
        "train",
        "val",
        "test",
    ]:

        count = int(
            (
                patch_df["split"]
                == split
            ).sum()
        )

        log(
            f"{split.capitalize():5s}: "
            f"{count}"
        )

    # --------------------------------------------------------
    # Verify-only mode
    # --------------------------------------------------------

    if args.verify_only:

        config = create_normalization_config(
            statistics=None,
            range_validation=None,
        )

        config_path = (
            output_dir
            / "normalization_config.json"
        )

        with config_path.open(
            "w",
            encoding="utf-8",
        ) as f:

            json.dump(
                config,
                f,
                indent=2,
            )

        log()
        log(
            f"Saved: {config_path}"
        )

        log()
        log(
            "STATUS: NORMALIZATION CONFIG VERIFIED"
        )

        return

    # --------------------------------------------------------
    # Statistics
    # --------------------------------------------------------

    statistics = (
        compute_training_statistics(
            patch_index=patch_df,
            data_root=data_root,
            sample_patches=args.sample_patches,
            seed=args.seed,
        )
    )

    # --------------------------------------------------------
    # Range validation
    # --------------------------------------------------------

    range_validation = (
        validate_dataset_ranges(
            patch_index=patch_df,
            data_root=data_root,
            sample_patches=min(
                args.sample_patches,
                len(patch_df),
            ),
            seed=args.seed,
        )
    )

    # --------------------------------------------------------
    # Configuration
    # --------------------------------------------------------

    config = create_normalization_config(
        statistics=statistics,
        range_validation=range_validation,
    )

    # --------------------------------------------------------
    # Save statistics
    # --------------------------------------------------------

    statistics_path = (
        output_dir
        / "training_reflectance_statistics.json"
    )

    with statistics_path.open(
        "w",
        encoding="utf-8",
    ) as f:

        json.dump(
            statistics,
            f,
            indent=2,
        )

    # --------------------------------------------------------
    # Save configuration
    # --------------------------------------------------------

    config_path = (
        output_dir
        / "normalization_config.json"
    )

    with config_path.open(
        "w",
        encoding="utf-8",
    ) as f:

        json.dump(
            config,
            f,
            indent=2,
        )

    # --------------------------------------------------------
    # Final output
    # --------------------------------------------------------

    log()
    log("=" * 72)
    log("NORMALIZATION COMPLETE")
    log("=" * 72)

    log(
        f"Statistics: "
        f"{statistics_path}"
    )

    log(
        f"Configuration: "
        f"{config_path}"
    )

    log()
    log("Per-band TRAIN statistics:")

    for band_index, band_name in enumerate(
        BAND_NAMES
    ):

        mean = statistics["mean"][
            band_index
        ]

        std = statistics["std"][
            band_index
        ]

        minimum = statistics["min"][
            band_index
        ]

        maximum = statistics["max"][
            band_index
        ]

        log(
            f"{band_name:4s} | "
            f"mean={mean:.6f} | "
            f"std={std:.6f} | "
            f"min={minimum:.6f} | "
            f"max={maximum:.6f}"
        )

    log()
    log(
        "STATUS: NORMALIZATION READY"
    )


if __name__ == "__main__":
    main()